# Generated by Django 5.0.6 on 2024-08-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testss',
        ),
    ]
